defaults: &defaults
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: localhost
  username: your_application_specific_username
  password: your_application_specific_password

test: &test
  database: activerecord_random
  <<: *defaults

cucumber:
  <<: *test